### ISSUE TITLE
Generating empty features

### ISSUE THREAD

**Issue by steveshi7** [node-geojson/geojson-random#17]
Script is generating a FeatureCollection of 'count' items, but each item is empty, regardless of parameters. True for all functions; tested random.point, random.polygon, random.lineString. Example input and output:

`console.log(random.point(10))`

> { type: 'FeatureCollection',
  features: 
   [ { type: 'Feature', geometry: [Object], properties: {} },
     { type: 'Feature', geometry: [Object], properties: {} },
     { type: 'Feature', geometry: [Object], properties: {} },
     { type: 'Feature', geometry: [Object], properties: {} },
     { type: 'Feature', geometry: [Object], properties: {} },
     { type: 'Feature', geometry: [Object], properties: {} },
     { type: 'Feature', geometry: [Object], properties: {} },
     { type: 'Feature', geometry: [Object], properties: {} },
     { type: 'Feature', geometry: [Object], properties: {} },
     { type: 'Feature', geometry: [Object], properties: {} } ] }

Note: pointstream seems to be working. Anyway to apply a bbox to a pointstream?

**Comment by tmcw** [comment]
Could you elaborate on what you mean by 'empty'? The provided output looks correct to me. If you're referring to the 'Object', that's a default behavior of console.log that can be avoided by using JSON.stringify

**Comment by steveshi7** [comment]
JSON.stringify fixed it. Sorry, I'm pretty new to JS!

**Comment by tmcw** [comment]
No worries, glad that worked!
