### ISSUE TITLE
draw perfect hexagon that will not overlap each other

### ISSUE THREAD

**Issue by MrHazimAli** [node-geojson/geojson-random#18]
Hye, Im thinking is this library generate geojson which have perfect hexagon and will not overlap each other?

something like this :- 
<img width="672" alt="screen shot 2018-01-23 at 2 46 43 pm" src="https://user-images.githubusercontent.com/6757574/35261824-e3818642-004c-11e8-9ce8-2c5642eac960.png">

Thank you!

**Comment by tmcw** [comment]
Nope, this generates random GeoJSON, as it says on the tin. You might be looking for @turfjs.
